# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7133cc06bcec883337506af1bf528c4361b4891e45c8fddfcdff8effe63e1395aa93eb7eda38ebfe54c54977cd364cef3123c78da8ea0a951beb4077001c7efa

test:
  secret_key_base: 34e89191eafc4816a5b0b1eaca5fae33946131d2856d6dfe84878b0f4d4ad16ccbcaf6218ad5ce8e944c05aaa5625acf1f5c725ac1f4df36376c2bf138f0f97e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
